### ISSUE TITLE
can't catch error

### ISSUE THREAD

**Issue by gutenye** [webpod/zurk#22]
Given this code

```ts
try {
  await $`exit 1`
} catch (error) {
  console.log('foo')
}
```

Output

It doesn't catch the error

```
error: Command failed with exit code 1
  at getError (zurk/target/esm/zurk.mjs:68:27)
  at callback (zurk/target/esm/zurk.mjs:22:40)
```

Expected

It catches the error

```
foo
```

**Comment by antongolub** [comment]
@gutenye,

Thanks for highlighting the issue. Fixed in [v0.6.3](https://github.com/webpod/zurk/releases/tag/v0.6.3)
